### PR TITLE
Fix prop types in Section and Grid to prevent yellow box warnings

### PR DESCRIPTION
**Pull request by DaKaZ**

### CODE REVIEW

**Comment by shouse** [comment]
Nice one @DaKaZ !  I'm getting this too.

**Comment by shouse** [comment]
Yes!  I'm running into this as well @DaKaZ.  This should be easy to review.  @MislavMandaric - any chance you could check it out soon and merge?

**Comment by srolija** [comment]
Hi, thank you for contribution.

I will merge the PR, we just need to update master to the new circleci build script, I have opened the PR to do so https://github.com/axilis/react-native-responsive-layout/pull/42 once it is merged tomorrow, you can rebase on master and we will release patch update to npm.

**Comment by srolija** [comment]
The test is failing since the peer dependency for library is older version react-native which doesn't have the support for `ViewPropTypes`: https://github.com/facebook/react-native/issues/14032#issuecomment-360607525

Likely we can bump the peer-dependency version since the one referenced is outdated these days.

**Comment by DaKaZ** [comment]
@srolija Please see the updated deps I needed to complete this PR.

**Comment by srolija** [comment]
Seems ok, can you just update the README.md to mention it RN 0.52 is a requirement. Then I will merge it to master.

**Comment by DaKaZ** [comment]
@srolija sorry for the delay, its updated  👍

**Comment by shouse** [comment]
Sweet!  One of my yellow warnings is about to go away!

**Comment by shouse** [comment]
@srolija Does the README.md update look good?

**Comment by srolija** [comment]
Yeah, I merged it, will bump up version and release it to npm this weekend, in meanwhile you can reference the master commit.

**Pull request merged**
